<a href="https://colab.research.google.com/github/cocoaswifty/PythonExercise/blob/master/100%2B_NumPy_Exercises_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
import numpy as np

In [81]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 
D = np.array([0.1, 0.3])
 
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.all(array)}')

A: True
B: False
C: False
D: True


In [82]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])
 
B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])
 
C = np.array([[True, False, False],
              [True, True, True]])
 
for name, array in zip(list('ABC'), [A, B, C]):
    print(f'{name}: {np.all(array, axis=1)}')

A: [ True  True]
B: [ True False]
C: [False  True]


In [83]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])
 
B = np.array([[0, 0, 0],
              [0, 1, 0]])
 
C = np.array([[False, False, False],
              [True, False, False]])
 
D = np.array([[0.1, 0.0]])
 
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array)}')

A: False
B: True
C: True
D: True


In [84]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])
 
B = np.array([[0, 0, 0],
              [0, 1, 0]])
 
C = np.array([[False, False, False],
              [True, False, False]])
 
D = np.array([[0.1, 0.0]])
 
for name, array in zip(list('ABCD'), [A, B, C, D]):
    print(f'{name}: {np.any(array, axis=0)}')

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


In [85]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
 
print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


In [86]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
 
print(np.allclose(A, B))

True


In [87]:

A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
 
print(A == B)

[False False  True]


In [88]:

A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
 
print(A > B)

[ True False False False]


In [89]:
print(np.zeros(shape=(4, 4), dtype='int'))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [90]:

print(np.ones(shape=(10, 10), dtype='float') * 255)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]


In [91]:

print(np.arange(10, 100))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58
 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [92]:

print(np.arange(10, 100).reshape(-1, 10)) 

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


In [93]:

print(np.eye(N=6, dtype='int'))

[[1 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 1 0 0 0]
 [0 0 0 1 0 0]
 [0 0 0 0 1 0]
 [0 0 0 0 0 1]]


In [94]:

np.random.seed(10)
print(np.random.rand(30))

[0.77132064 0.02075195 0.63364823 0.74880388 0.49850701 0.22479665 0.19806286 0.76053071 0.16911084 0.08833981 0.68535982 0.95339335 0.00394827
 0.51219226 0.81262096 0.61252607 0.72175532 0.29187607 0.91777412 0.71457578 0.54254437 0.14217005 0.37334076 0.67413362 0.44183317 0.43401399
 0.61776698 0.51313824 0.65039718 0.60103895]


In [95]:

 
np.random.seed(20)
print(np.random.randn(10, 4))

[[ 0.88389311  0.19586502  0.35753652 -2.34326191]
 [-1.08483259  0.55969629  0.93946935 -0.97848104]
 [ 0.50309684  0.40641447  0.32346101 -0.49341088]
 [-0.79201679 -0.84236793 -1.27950266  0.24571517]
 [-0.0441948   1.56763255  1.05110868  0.40636843]
 [-0.1686461  -3.18970279  1.12013226  1.33277821]
 [-0.24333877 -0.13003071 -0.10901737  1.55618644]
 [ 0.12877835 -2.06694872 -0.88549315 -1.10457948]
 [ 0.93286635  2.059838   -0.93493796 -1.61299022]
 [ 0.52706972 -1.55110074  0.32961334 -1.13652654]]


In [96]:

np.random.seed(30)
 
sigma = np.sqrt(5)
mu = 100
 
print(sigma * np.random.randn(10, 4) + mu)

[[ 97.17349231 103.41650023  97.82942436 101.05220329]
 [ 99.7748353  100.67930221  96.14063068 103.544381  ]
 [100.30029631  97.52499594 103.52901961 100.24037271]
 [ 98.29153712  98.2666258  103.09437633 101.70027274]
 [ 99.36127721 101.20382627  95.34026547 102.09694365]
 [ 99.98708001  98.95468525  99.05410904 102.38025432]
 [ 93.50787269 103.61547679 103.18753701  98.51356237]
 [102.20256689  96.19764407  97.54000366  97.05813038]
 [101.81233513  97.66380453  98.45883627  98.09317768]
 [102.48979932  95.70413391  98.43161651 101.89861815]]


In [97]:

 
A = np.array([[1, 4, 3],
              [5, 2, 6]])
 
for i in np.nditer(A):
    print(i)

1
4
3
5
2
6


In [98]:
print(np.linspace(start=0, stop=1, num=11))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [99]:
np.random.seed(42)
print(np.random.choice(range(1, 50), size=6, replace=False))

[14 46 48 45 18 28]


In [100]:

print(np.diag(np.arange(6)))

[[0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]
 [0 0 0 0 0 5]]


In [101]:

A = np.arange(12).reshape(-1, 4)
np.save('array.npy', A)
 
B = np.load('array.npy')
print(B)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [102]:

A = np.arange(12, dtype='int').reshape(-1, 4)
np.savetxt(fname='array.txt', X=A, fmt='%0.2f')
 
B = np.loadtxt('array.txt')
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [103]:

A = np.arange(12, dtype='int').reshape(-1, 4)
print(A.tolist())

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [104]:
A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [105]:

A = np.ones(shape=(4, 4))
print(np.pad(A, pad_width=1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [106]:
 
A = np.zeros(shape=(6, 6), dtype='int')
A[::2, ::2] = 10
A[1::2, ::2] = 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


In [107]:

A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
 
print(np.append(A, B, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


In [108]:

 
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])
 
print(np.intersect1d(A, B))

[0 2 3]


In [109]:

np.random.seed(10)
A = np.random.randint(low=1, high=10, size=(3, 5))
print(np.unique(A))

[1 2 4 5 7 9]


In [110]:

A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
 
print(np.argmax(A, axis=1))

[0 2 1]


In [111]:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
 
print(np.sort(A))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


In [112]:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
 
print(A[A > 8])

[ 9.99  9.99 14.99]


In [113]:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
 
print(np.where(A > 10.0, 10.0, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


In [114]:

 
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
 
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


In [115]:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
 
print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [116]:

A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
 
print(np.full_like(A, 9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


In [117]:

print(np.tri(N=5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [118]:

A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],
              
              [[7, 2, 3, 1],
               [6, 2, 0, 9],
               [0, 1, 9, 1]]])

In [119]:

image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)

In [120]:
image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)
image_sorted = np.sort(image)

In [121]:

A = np.array([[4, 2, 1],
              [6, 4, 2]])
 
print(np.expand_dims(A, axis=0))

[[[4 2 1]
  [6 4 2]]]


In [122]:

np.random.seed(42)
 
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(image)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


In [123]:

image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image_expanded = np.expand_dims(image, axis=0)

In [124]:

image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
 
image1 = np.expand_dims(image1, axis=0)
image2 = np.expand_dims(image2, axis=0)
 
images = np.append(image1, image2, axis=0)

In [125]:
 
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
 
print(np.squeeze(A))

[[1 2 3]
 [6 3 2]]


In [126]:

A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
 
print(np.squeeze(A))

[0.4 0.9 0.5 0.6]


In [127]:

A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[:, ::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [128]:

A = np.arange(12, dtype='int').reshape(-1, 4)
print(A[::-1, ::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [129]:

np.random.seed(42)
 
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
print(image[:, :, 0])

[[102  95 234   3  14  46  99 212 188 153]
 [203 214 121 114 239 244  74  14 145 184]
 [116  85 226 235 151 181 160   6  52  14]
 [ 76 233 235 213  68 219 129   0 140 147]
 [ 20  46  19 209  57 156  86  24 235 110]
 [231 254 218 134 162  73 169  35 242 253]
 [187 249 201 231 189 116  49  74 189 158]
 [ 29   7  54 131 181 123 248 119 228  13]
 [ 50 155  40 120  72 115 167  85 131 242]
 [ 52 169  13 144 243 167   8  77  22  10]]


In [130]:

image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)
result = image[:5, :5, :]

In [131]:

A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
 
print(np.concatenate((A, B), axis=0))

[[3 4 5]
 [8 3 1]
 [0 5 2]
 [4 2 1]]


In [132]:

data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
 
print(np.concatenate((data, target), axis=1))

[[4.3 4.2 0. ]
 [3.1 3.6 1. ]]


In [133]:
 
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
 
print(np.column_stack((feature1, feature2, feature3)))

[[1.6 0.4 1.4]
 [0.9 1.3 0.3]
 [2.2 3.2 1.2]]


In [134]:

np.random.seed(42)
 
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
 
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[4 6 2 4]
 [6 2 2 4]
 [1 3 5 5]
 [3 1 5 4]
 [2 6 1 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [135]:
 
np.random.seed(42)
 
 
A = np.random.randint(low=0, high=2, size=(10, 6))
 
print(np.count_nonzero(A))

31


In [136]:

np.random.seed(42)
 
A = np.random.randn(10, 4)
 
np.set_printoptions(precision=4)
print(A)

[[ 0.4967 -0.1383  0.6477  1.523 ]
 [-0.2342 -0.2341  1.5792  0.7674]
 [-0.4695  0.5426 -0.4634 -0.4657]
 [ 0.242  -1.9133 -1.7249 -0.5623]
 [-1.0128  0.3142 -0.908  -1.4123]
 [ 1.4656 -0.2258  0.0675 -1.4247]
 [-0.5444  0.1109 -1.151   0.3757]
 [-0.6006 -0.2917 -0.6017  1.8523]
 [-0.0135 -1.0577  0.8225 -1.2208]
 [ 0.2089 -1.9597 -1.3282  0.1969]]


In [137]:

A = np.array([1.2e-6, 1.7e-7])
 
np.set_printoptions(suppress=True, precision=8)
print(A)

[0.0000012  0.00000017]


In [138]:

np.random.seed(42)
 
A = np.random.randn(8, 4)
print(np.delete(A, [2], axis=1))

[[ 0.49671415 -0.1382643   1.52302986]
 [-0.23415337 -0.23413696  0.76743473]
 [-0.46947439  0.54256004 -0.46572975]
 [ 0.24196227 -1.91328024 -0.56228753]
 [-1.01283112  0.31424733 -1.4123037 ]
 [ 1.46564877 -0.2257763  -1.42474819]
 [-0.54438272  0.11092259  0.37569802]
 [-0.60063869 -0.29169375  1.85227818]]


In [139]:

v = np.array([3, 4, -2])
print(np.linalg.norm(v))

5.385164807134504


In [140]:

np.random.seed(42)
A = np.random.randint(10, size=(100, 30))
 
np.set_printoptions(edgeitems=10)
print(A)

[[6 3 7 4 6 9 2 6 7 4 ... 4 0 9 5 8 0 9 2 6 3]
 [8 2 4 2 6 4 8 6 1 3 ... 2 0 3 1 7 3 1 5 5 9]
 [3 5 1 9 1 9 3 7 6 8 ... 6 8 7 0 7 7 2 0 7 2]
 [2 0 4 9 6 9 8 6 8 7 ... 0 2 4 2 0 4 9 6 6 8]
 [9 9 2 6 0 3 3 4 6 6 ... 9 6 8 6 0 0 8 8 3 8]
 [2 6 5 7 8 4 0 2 9 7 ... 2 0 4 0 7 0 0 1 1 5]
 [6 4 0 0 2 1 4 9 5 6 ... 5 0 8 5 2 3 3 2 9 2]
 [2 3 6 3 8 0 7 6 1 7 ... 3 0 1 0 4 4 6 8 8 2]
 [2 2 3 7 5 7 0 7 3 0 ... 1 1 5 2 8 3 0 3 0 4]
 [3 7 7 6 2 0 0 2 5 6 ... 4 2 3 2 0 0 4 5 2 8]
 ...
 [6 4 8 2 0 3 8 3 1 9 ... 8 4 7 1 5 2 9 4 7 9]
 [0 4 2 3 1 8 2 1 9 8 ... 7 7 6 5 8 3 0 7 6 6]
 [2 3 9 8 5 4 2 8 4 4 ... 6 1 7 5 3 4 7 2 2 3]
 [0 8 7 7 9 5 6 5 8 2 ... 2 3 7 5 4 3 7 0 8 0]
 [7 3 8 4 2 8 8 3 3 7 ... 4 4 3 4 2 0 4 8 8 3]
 [2 0 1 7 0 7 6 7 5 8 ... 2 3 6 6 3 5 2 5 1 7]
 [1 6 8 0 7 6 5 5 5 8 ... 2 7 2 3 7 0 5 0 0 7]
 [3 0 9 6 4 4 0 9 5 8 ... 6 8 6 2 0 7 2 7 7 4]
 [0 9 6 9 4 7 8 6 6 0 ... 7 3 0 0 9 2 8 6 1 8]
 [9 1 2 9 1 2 5 8 8 6 ... 8 2 0 6 9 4 4 0 8 6]]


In [141]:
 
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print((A + B) / 2)

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


In [142]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
 
print(A * B)


[[12 12 18 10]
 [30  9  2 30]]


In [143]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
 
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


In [144]:
 
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype='float')
 
print(np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B))

True


In [145]:
 
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
 
print(np.dot(A, B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


In [146]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
 
print(np.linalg.det(A))

51.999999999999986


In [147]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
 
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-0.62616472 -0.89442719  0.89015941]
 [-0.31308236  0.          0.4450797 ]
 [ 0.71407086  0.4472136  -0.09757197]]


In [148]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
 
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


In [149]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
 
print(np.trace(A))

-5


In [150]:
A = np.array([[2, 0],
              [4, 2],
              [5, 3],
              [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])
print(np.dot(A, B.reshape(2, -1)))

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]


In [151]:
np.random.seed(42)
 
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
 
np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['002' '4.99']
 ['005' '1.49']
 ['003' '7.99']
 ['001' '14.99']
 ['004' '2.49']]


In [152]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
 
print(np.argsort(A))

[5 2 1 0 4 3]


In [153]:
np.random.seed(42)
A = np.random.randn(10, 8)
 
print(np.round(A, decimals=3))

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]


In [154]:
W = np.array([4, 5, 1])
print(np.roots(W))

[-1.   -0.25]


In [155]:
Q = np.array([2, 4, -5, 1])
R = np.array([2, 0, -5, 1])
 
print(np.roots(Q))
print(np.roots(R))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


In [156]:
W = np.array([4, 5, 1])
Q = np.array([2, 4, -5, 1])
 
print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


In [157]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
 
print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]


In [158]:
print(np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]'))

['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05' '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10' '2021-01-11'
 '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15' '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20' '2021-01-21' '2021-01-22'
 '2021-01-23' '2021-01-24' '2021-01-25' '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30' '2021-01-31']


In [159]:
A = np.arange('2021-01', '2022-01', dtype='datetime64[M]')
A = A.reshape(-1, 3)
print(A)

[['2021-01' '2021-02' '2021-03']
 ['2021-04' '2021-05' '2021-06']
 ['2021-07' '2021-08' '2021-09']
 ['2021-10' '2021-11' '2021-12']]


In [160]:

print(np.datetime64('today'))

2021-04-13


In [161]:
print(np.arange('2020-01-06', '2020-03', dtype='datetime64[D]')[::7])

['2020-01-06' '2020-01-13' '2020-01-20' '2020-01-27' '2020-02-03' '2020-02-10' '2020-02-17' '2020-02-24']


In [162]:
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)
 
print(np.char.add(A, B))

['001XC' '002YC' '003ZC']


In [163]:
A = np.array(['1', '2', '3'], dtype=np.str)
 
print(np.char.add('000', A))

['0001' '0002' '0003']


In [164]:
A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)
 
print(np.char.split(A))

[[list(['PLW', 'CDR', '11B', 'TEN']) list(['AMC', 'LPP'])]
 [list(['CDR', 'PKO', 'KGH']) list(['CCC', 'QMK'])]]


In [165]:
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
 
print(np.char.strip(np.char.replace(A, '#', ' ')))

[['summer time mood']
 ['sport time']]


In [166]:
A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])
 
print(np.char.count(A, 'time'))

[[1 0]
 [1 1]
 [0 0]]


In [167]:
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""
 
lines = text.splitlines()
lines = [line.split('\t') for line in lines]
result = np.array(lines, dtype=np.str)
print(result)


[['ALIOR' 'PLALIOR00045' '88 860 000' '1 386 216 000' '0,891' '2,16' '14']
 ['CCC' 'PLCCC0000016' '27 918 000' '1 292 603 400' '0,831' '5,28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67 348 000' '22 864 646 000' '14,702' '7,39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275 301 000' '6 854 994 900' '4,408' '1,17' '14']
 ['DINOPL' 'PLDINPL00011' '47 937 000' '8 916 282 000' '5,733' '9,13' '12']
 ['JSW' 'PLJSW0000015' '52 636 000' '716 902 320' '0,461' '1,51' '24']
 ['KGHM' 'PLKGHM000017' '136 410 000' '9 881 540 400' '6,354' '4,78' '8']
 ['LOTOS' 'PLLOTOS00025' '86 543 000' '5 609 717 260' '3,607' '2,91' '16']
 ['LPP' 'PLLPP0000011' '1 306 000' '7 444 200 000' '4,787' '1,43' '19']
 ['MBANK' 'PLBRE0000012' '12 997 000' '2 830 746 600' '1,820' '0,42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647 357 000' '4 285 503 340' '2,756' '1,16' '13']
 ['PEKAO' 'PLPEKAO00016' '176 379 000' '9 619 710 660' '6,185' '5,27' '9']
 ['PGE' 'PLPGER000010' '796 776 000' '3 561 588 720' '2,290' '2,88' '18']
 ['PGNIG' 'PLPGNIG000

In [168]:

np.set_printoptions(linewidth=150)
result = np.array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891', '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831', '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000', '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900', '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733', '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461', '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354', '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607', '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787', '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820', '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647 357 000', '4 285 503 340', '2,756', '1,16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176 379 000', '9 619 710 660', '6,185', '5,27', '9'],
       ['PGE', 'PLPGER000010', '796 776 000', '3 561 588 720', '2,290', '2,88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1 624 608 000', '6 072 784 704', '3,905', '1,56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289 049 000', '17 701 360 760', '11,382', '12,44', '8'],
       ['PKOBP', 'PLPKO0000016', '857 593 000', '18 807 014 490', '12,093', '10,49', '9'],
       ['PLAY', 'LU1642887738', '114 151 000', '3 696 209 380', '2,377', '1,47', '16'],
       ['PZU', 'PLPZU0000011', '568 305 000', '17 515 160 100', '11,262', '6,64', '6'],
       ['SANPL', 'PLBZ00000044', '33 207 000', '5 213 499 000', '3,352', '1,91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1 043 590 000', '1 252 308 000', '0,805', '1,21', '33']], dtype='<U14')
 
result = np.char.replace(result, ' ', '')
result = np.char.replace(result, ',', '.')
print(result)

[['ALIOR' 'PLALIOR00045' '88860000' '1386216000' '0.891' '2.16' '14']
 ['CCC' 'PLCCC0000016' '27918000' '1292603400' '0.831' '5.28' '42']
 ['CDPROJEKT' 'PLOPTTC00011' '67348000' '22864646000' '14.702' '7.39' '7']
 ['CYFRPLSAT' 'PLCFRPT00013' '275301000' '6854994900' '4.408' '1.17' '14']
 ['DINOPL' 'PLDINPL00011' '47937000' '8916282000' '5.733' '9.13' '12']
 ['JSW' 'PLJSW0000015' '52636000' '716902320' '0.461' '1.51' '24']
 ['KGHM' 'PLKGHM000017' '136410000' '9881540400' '6.354' '4.78' '8']
 ['LOTOS' 'PLLOTOS00025' '86543000' '5609717260' '3.607' '2.91' '16']
 ['LPP' 'PLLPP0000011' '1306000' '7444200000' '4.787' '1.43' '19']
 ['MBANK' 'PLBRE0000012' '12997000' '2830746600' '1.820' '0.42' '24']
 ['ORANGEPL' 'PLTLKPL00017' '647357000' '4285503340' '2.756' '1.16' '13']
 ['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 

In [169]:

np.set_printoptions(linewidth=150)
result = np.array([['ALIOR', 'PLALIOR00045', '88860000', '1386216000', '0.891', '2.16', '14'],
       ['CCC', 'PLCCC0000016', '27918000', '1292603400', '0.831', '5.28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67348000', '22864646000', '14.702', '7.39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275301000', '6854994900', '4.408', '1.17', '14'],
       ['DINOPL', 'PLDINPL00011', '47937000', '8916282000', '5.733', '9.13', '12'],
       ['JSW', 'PLJSW0000015', '52636000', '716902320', '0.461', '1.51', '24'],
       ['KGHM', 'PLKGHM000017', '136410000', '9881540400', '6.354', '4.78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86543000', '5609717260', '3.607', '2.91', '16'],
       ['LPP', 'PLLPP0000011', '1306000', '7444200000', '4.787', '1.43', '19'],
       ['MBANK', 'PLBRE0000012', '12997000', '2830746600', '1.820', '0.42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647357000', '4285503340', '2.756', '1.16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6'],
       ['SANPL', 'PLBZ00000044', '33207000', '5213499000', '3.352', '1.91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1043590000', '1252308000', '0.805', '1.21', '33']], dtype='<U12')
 
stocks_startswith_P = result[np.char.startswith(result[:, 0], 'P')]
print(stocks_startswith_P)

[['PEKAO' 'PLPEKAO00016' '176379000' '9619710660' '6.185' '5.27' '9']
 ['PGE' 'PLPGER000010' '796776000' '3561588720' '2.290' '2.88' '18']
 ['PGNIG' 'PLPGNIG00014' '1624608000' '6072784704' '3.905' '1.56' '12']
 ['PKNORLEN' 'PLPKN0000018' '289049000' '17701360760' '11.382' '12.44' '8']
 ['PKOBP' 'PLPKO0000016' '857593000' '18807014490' '12.093' '10.49' '9']
 ['PLAY' 'LU1642887738' '114151000' '3696209380' '2.377' '1.47' '16']
 ['PZU' 'PLPZU0000011' '568305000' '17515160100' '11.262' '6.64' '6']]


In [170]:
np.set_printoptions(linewidth=150)
stocks_startswith_P = np.array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6']], dtype='<U12')
 
print(np.round(stocks_startswith_P[:, 4].astype(float).sum(), 2))

49.49


In [171]:
np.set_printoptions(linewidth=160, suppress=True)
 
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""
 
lines = wig_games_raw.splitlines()
lines = [line.split('\t') for line in lines]
wig_games = np.array(lines, dtype=np.str)
wig_games = np.char.replace(wig_games, ' ', '')
print(wig_games)

[['Profile' 'Time' 'Course' 'Change' 'Change%' 'Ref.' 'Open' 'Low' 'High' 'Volume' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '+8.00' '(+2.09%)' '383.00' '383.50' '383.00' '394.00' '12784' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '+5.30' '(+1.59%)' '334.20' '338.30' '337.00' '344.20' '233059' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '-0.012' '(-1.59%)' '0.754' '0.772' '0.730' '0.772' '1311078' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '+18.00' '(+4.87%)' '369.50' '374.00' '373.00' '388.00' '33206' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '+22.50' '(+6.88%)' '327.00' '332.00' '330.00' '353.50' '39793' '13697060' '28.855%']]


In [172]:
np.set_printoptions(linewidth=160, suppress=True)
 
wig_games = np.array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')
 
wig_games = np.delete(wig_games, [3, 4, 5, 9], axis=1)
print(wig_games)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


In [173]:
np.set_printoptions(linewidth=160, suppress=True)
 
wig_games = np.array([['Profile', 'Time', 'Course', 'Open', 'Low', 'High', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '383.50', '383.00', '394.00', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '338.30', '337.00', '344.20', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '0.772', '0.730', '0.772', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '374.00', '373.00', '388.00', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '332.00', '330.00', '353.50', '13697060', '28.855%']], dtype='<U14')
 
np.savetxt(fname='wig_games.csv', X=wig_games, fmt='%s', delimiter=',')
wig_games_new = np.loadtxt(fname='wig_games.csv', delimiter=',', dtype=str)
print(wig_games_new)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


In [174]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""
 
lines = playway_raw.splitlines()
lines = [line.split(',') for line in lines]
playway = np.array(lines, dtype=np.str)
print(playway)

[['Date' 'Open' 'High' 'Low' 'Close' 'Volume']
 ['2020-03-02' '305' '324.5' '283.5' '310' '64081']
 ['2020-03-03' '325.5' '340.5' '320' '340.5' '55496']
 ['2020-03-04' '324' '340.5' '315' '330' '36152']
 ['2020-03-05' '344' '344' '310' '315' '35992']
 ['2020-03-06' '306.5' '307' '291' '305' '32539']
 ['2020-03-09' '274' '291' '250' '258' '79402']
 ['2020-03-10' '278' '284.5' '256' '264' '35700']
 ['2020-03-11' '270' '270' '238.5' '245' '60445']
 ['2020-03-12' '218' '228' '196' '197' '94031']
 ['2020-03-13' '210' '229' '198.8' '211' '100412']
 ['2020-03-16' '205' '248' '197.8' '240.5' '50659']
 ['2020-03-17' '245' '269' '232.5' '264' '99480']
 ['2020-03-18' '264' '280' '251' '270' '70136']
 ['2020-03-19' '267' '280' '267' '279.5' '30732']
 ['2020-03-20' '297.5' '307' '280' '280.5' '43426']
 ['2020-03-23' '274' '289' '258' '285' '37098']
 ['2020-03-24' '305' '309' '296.5' '309' '31939']
 ['2020-03-25' '313' '330' '295' '304' '46724']
 ['2020-03-26' '300' '309' '295.5' '300' '27213']
 ['2

In [175]:
playway = np.array([['Date', 'Open', 'High', 'Low', 'Close', 'Volume'],
       ['2020-03-02', '305', '324.5', '283.5', '310', '64081'],
       ['2020-03-03', '325.5', '340.5', '320', '340.5', '55496'],
       ['2020-03-04', '324', '340.5', '315', '330', '36152'],
       ['2020-03-05', '344', '344', '310', '315', '35992'],
       ['2020-03-06', '306.5', '307', '291', '305', '32539'],
       ['2020-03-09', '274', '291', '250', '258', '79402'],
       ['2020-03-10', '278', '284.5', '256', '264', '35700'],
       ['2020-03-11', '270', '270', '238.5', '245', '60445'],
       ['2020-03-12', '218', '228', '196', '197', '94031'],
       ['2020-03-13', '210', '229', '198.8', '211', '100412'],
       ['2020-03-16', '205', '248', '197.8', '240.5', '50659'],
       ['2020-03-17', '245', '269', '232.5', '264', '99480'],
       ['2020-03-18', '264', '280', '251', '270', '70136'],
       ['2020-03-19', '267', '280', '267', '279.5', '30732'],
       ['2020-03-20', '297.5', '307', '280', '280.5', '43426'],
       ['2020-03-23', '274', '289', '258', '285', '37098'],
       ['2020-03-24', '305', '309', '296.5', '309', '31939'],
       ['2020-03-25', '313', '330', '295', '304', '46724'],
       ['2020-03-26', '300', '309', '295.5', '300', '27213'],
       ['2020-03-27', '302', '306.5', '290', '296', '13466'],
       ['2020-03-30', '299', '300', '287', '300', '10316'],
       ['2020-03-31', '302.5', '309', '302', '306.5', '15698']],
      dtype='<U10')
 
playway = np.delete(playway, [0], axis=1)
playway_values = playway[1:].astype(float)
print(playway_values)

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

In [176]:
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
 
print(np.round(playway_values.mean(axis=0), 2))

[  283.14   295.25   268.69   282.3  48688.05]


In [177]:
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ],
       [   325.5,    340.5,    320. ,    340.5,  55496. ],
       [   324. ,    340.5,    315. ,    330. ,  36152. ],
       [   344. ,    344. ,    310. ,    315. ,  35992. ],
       [   306.5,    307. ,    291. ,    305. ,  32539. ],
       [   274. ,    291. ,    250. ,    258. ,  79402. ],
       [   278. ,    284.5,    256. ,    264. ,  35700. ],
       [   270. ,    270. ,    238.5,    245. ,  60445. ],
       [   218. ,    228. ,    196. ,    197. ,  94031. ],
       [   210. ,    229. ,    198.8,    211. , 100412. ],
       [   205. ,    248. ,    197.8,    240.5,  50659. ],
       [   245. ,    269. ,    232.5,    264. ,  99480. ],
       [   264. ,    280. ,    251. ,    270. ,  70136. ],
       [   267. ,    280. ,    267. ,    279.5,  30732. ],
       [   297.5,    307. ,    280. ,    280.5,  43426. ],
       [   274. ,    289. ,    258. ,    285. ,  37098. ],
       [   305. ,    309. ,    296.5,    309. ,  31939. ],
       [   313. ,    330. ,    295. ,    304. ,  46724. ],
       [   300. ,    309. ,    295.5,    300. ,  27213. ],
       [   302. ,    306.5,    290. ,    296. ,  13466. ],
       [   299. ,    300. ,    287. ,    300. ,  10316. ],
       [   302.5,    309. ,    302. ,    306.5,  15698. ]])
 
max_min_diff = playway_values[:, [1]] - playway_values[:, [2]]
playway_values = np.concatenate((playway_values, max_min_diff), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     295.    

In [178]:
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
                           [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
                           [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
                           [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
                           [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
                           [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
                           [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
                           [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
                           [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
                           [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
                           [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
                           [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
                           [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
                           [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
                           [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
                           [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
                           [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
                           [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
                           [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
                           [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
                           [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
                           [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
 
print(playway_values[playway_values[:, 3] > 300.0])

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


In [179]:
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
                           [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
                           [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
                           [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
                           [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
                           [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
                           [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
                           [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
                           [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
                           [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
                           [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
                           [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
                           [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
                           [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
                           [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
                           [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
                           [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
                           [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
                           [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
                           [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
                           [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
                           [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
 
print(playway_values[playway_values[:, 4].argsort()[::-1]][:10])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


In [180]:
np.set_printoptions(suppress=True)
playway_values = np.array([[   305. ,    324.5,    283.5,    310. ,  64081. ,     41. ],
                           [   325.5,    340.5,    320. ,    340.5,  55496. ,     20.5],
                           [   324. ,    340.5,    315. ,    330. ,  36152. ,     25.5],
                           [   344. ,    344. ,    310. ,    315. ,  35992. ,     34. ],
                           [   306.5,    307. ,    291. ,    305. ,  32539. ,     16. ],
                           [   274. ,    291. ,    250. ,    258. ,  79402. ,     41. ],
                           [   278. ,    284.5,    256. ,    264. ,  35700. ,     28.5],
                           [   270. ,    270. ,    238.5,    245. ,  60445. ,     31.5],
                           [   218. ,    228. ,    196. ,    197. ,  94031. ,     32. ],
                           [   210. ,    229. ,    198.8,    211. , 100412. ,     30.2],
                           [   205. ,    248. ,    197.8,    240.5,  50659. ,     50.2],
                           [   245. ,    269. ,    232.5,    264. ,  99480. ,     36.5],
                           [   264. ,    280. ,    251. ,    270. ,  70136. ,     29. ],
                           [   267. ,    280. ,    267. ,    279.5,  30732. ,     13. ],
                           [   297.5,    307. ,    280. ,    280.5,  43426. ,     27. ],
                           [   274. ,    289. ,    258. ,    285. ,  37098. ,     31. ],
                           [   305. ,    309. ,    296.5,    309. ,  31939. ,     12.5],
                           [   313. ,    330. ,    295. ,    304. ,  46724. ,     35. ],
                           [   300. ,    309. ,    295.5,    300. ,  27213. ,     13.5],
                           [   302. ,    306.5,    290. ,    296. ,  13466. ,     16.5],
                           [   299. ,    300. ,    287. ,    300. ,  10316. ,     13. ],
                           [   302.5,    309. ,    302. ,    306.5,  15698. ,      7. ]])
 
flag = playway_values[:, [0]] < playway_values[:, [3]]
flag = flag.astype(int)
playway_values = np.concatenate((playway_values, flag), axis=1)
print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 

$ \begin{cases} 5x-3y=21 \\ x-2y=7 \end{cases} $

In [181]:
A = np.array([[5, -3], [1, -2]])
B = np.array([[21], [7]])
X = np.dot(np.linalg.inv(A), B)
x = X[0][0]
y = X[1][0]
print(f'x = {x:.2f}\ny = {y:.2f}')

x = 3.00
y = -2.00


$ \begin{cases} x+y+z=1 \\ 2x+y+5z=0 \\ x-y=z \end{cases} $


In [182]:
A = np.array([[1, 1, 1], [2, 1, 5], [1, -1, -1]])
B = np.array([[1], [0], [0]])
X = np.dot(np.linalg.inv(A), B)
x = X[0][0]
y = X[1][0]
z = X[2][0]
print(f'x = {x:.2f}\ny = {y:.2f}\nz = {z:.2f}')

x = 0.50
y = 0.88
z = -0.38
